main/home/routes.py
import sys
from . import db
from flask import (
    Flask, render_template,
    request, redirect, url_for,
    abort, flash, jsonify,
    make_response,
    Blueprint
)
from datetime import datetime as dt
from flask import current_app as app
from flask_sqlalchemy import SQLAlchemy

# Blueprint Configuration
home_bp = Blueprint(
    'home_bp', __name__,
    template_folder='templates'
)

@home_bp.route('/', methods=['GET'])
def home():
    """Homepage."""

    return render_template(
        'index.html',
        title='Flask Blueprint Demo',
        description='Demonstration of Flask blueprints in action.',
        template='home-template'
    )

main/templates/macros/_field.html
{% macro render_field(field) %}
    {{ field.label(class_="block mt-1 text-gray-700") }}
    {{ field(class_="mt-1 block w-full rounded-md border-gray-300 shadow focus:border-indigo-300 focus:ring focus:ring-indigo-200/50", **kwargs) |safe }}
    {% if field.errors %}
        <ul class=errors>
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}
{% endmacro %}

main/templates/macros/header.html
<div class="flex flex-row justify-between px-4 py-3 bg-gray-600 text-white ">
    {% include 'macros/navigation.html' %}
    <h3 class="text-center"><a href="{{ url_for('home_bp.home') }}">Home</a></h3>
    <nav class=" order-last" role='navigation'>
        <ul class="flex flex-row space-x-4">
            <li class="hover:text-gray-200"><a href="https://example.com">Link 2</a></li>
            <li class="hover:text-gray-200"><a href="https://example.com">Link 2</a></li>
        </ul>
    </nav>
</div>

main/templates/macros/navigation.html
<nav class="order-first" role='navigation'>
    <ul class="flex flex-row space-x-4">
        <li class="hover:text-gray-200"><a href="https://example.com">Link 1</a></li>
        <li class="hover:text-gray-200"><a href="https://example.com">Link 1</a></li>
    </ul>
</nav>